Project1/Firstapp/urls.py
from django.urls import path    #This will import path 
from . import views             #This will import views from the current directory 
urlpatterns = [
    #Defining the path that will be rendered on the request
    path("<str:name>" , views.greet , name="greet"),
    path("",views.index, name="index"),
    path("Ashutosh" , views.Ashutosh , name="Ashutosh"),
    path("David" , views.David , name="David") , 
    path("Malan" , views.Malan , name="Malan"),
    path("Brian" , views.Brian , name="Brian"),
    path("Havard" , views.Havard , name="Havard"),
    path("Mi" , views.Mi , name="Mi")
]

Project1/Project1/urls.py
from django.contrib import admin
from django.urls import include , path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Firstapp/' , include("Firstapp.urls")),
    path('newyear/' , include("newyear.urls")),
    path('tasks/' , include("tasks.urls"))
]

Project1/newyear/urls.py
from django.urls import path

from . import views 

urlpatterns = [
    path("" , views.index , name="index")
]

Project1/tasks/urls.py
from django.urls import path 
from . import views

#Adding the app name
app_name = "tasks"
urlpatterns = [
    path("" , views.index , name="index") ,
    #Adding the path for add function
    path("add" , views.add , name="add")
]

Project1/Firstapp/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request) :
    return render(request ,"Firstapp/index.html" ) 

#Adding a new function named by Ashutosh
def Ashutosh(request) :
    return HttpResponse("Hello , Ashutosh!")

#Now we will add more functions
def David(request):
    return HttpResponse("Hello , David!")

def Malan(request):
    return HttpResponse("Hello , Malan")

def Brian(request):
    return HttpResponse("Hello , Brian!")

def Havard(request):
    return HttpResponse("Hello , Harvard!")

def Mi (request):
    return HttpResponse("Hello , Mi!")

#Now we will add the function that will greet everyone who enters his name 
def greet(request , name):
    return render (request , "Firstapp/greet.html" , {
        "name": name.capitalize()
    })

Project1/newyear/views.py
import datetime
from django.shortcuts import render

# Create your views here.
def index (request):
    now = datetime.datetime.now()
    return render(request , "newyear/index.html" , {
        "newyear" : now.month == 1 and now.day == 1
    })

Project1/tasks/views.py
from django.shortcuts import render
from django import forms
tasks = ["Foo" , "Harry" , "George"]         #Defining the universal variable
# Create your views here.

#Adding a class to contain form
class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task : ")
    priority = forms.IntegerField(label="Priority")

def index(request):
    return render(request , "tasks/index.html" , {
        "tasks" : tasks
    })


#Adding new function to add the new lists
def add (request):
    return render (request , "tasks/add.html" , {
        "form" : NewTaskForm()
    })

Project1/Firstapp/templates/Firstapp/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        Greet
    </title>
</head>
<body>
    <h1>
        Hello , {{name}} ! 
    </h1>
</body>
</html>

Project1/Firstapp/templates/Firstapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>
        Hello Wrold ! 
    </h1>
</body>
</html>

Project1/newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>is it New Year ?</title>
    <link rel="stylesheet" href="{% static 'newyear/style.css'%}">
</head>
<body>
    {% if newyear  %} 
        <h1>
            YES
        </h1>
    {% else %}
        <h1>
            NO 
        </h1>
    {% endif %}
</body>
</html>

Project1/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
<h1>
    Add 
</h1>
<form action="{% url 'tasks:add' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
<a href="{% url 'tasks:index' %}">View Task</a>
{% endblock %}

Project1/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    {% for task in tasks %}
        <li>{{ task }}</li>
    {% endfor %}
    <a href="{% url 'tasks:add' %}">Add a New Task !</a>
{% endblock %}

Project1/tasks/templates/tasks/layout.html
<!---
    This file contains the common HTML code which we will use in add and index html    
---->


<!---Main code begins -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>